name: CraftEconomy
author: WatsonLLC
description: Realistic economy for Craft servers
version: 1.0.0
api-version: '1.21'
main: com.watsonllc.economyplugin.Economy
commands:
  balance:
    description: View your bank account balance
    aliases: [bal]
  baltop:
    description: View the richest players on the server
  bank:
    description: Access the bank manager
  economy:
    description: Base command for Economy plugin
  pay:
    description: Pay a player from your account